name: Rust Check

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  audit:
    uses: KyleChamberlin/.github/.github/workflows/rust-check.yml@main
