name: Rust Audit

on:
  push:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  issues: write
  security-events: write
  actions: read
  checks: read
  contents: read
  deployments: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read


jobs:
  audit:
    uses: KyleChamberlin/.github/.github/workflows/rust-audit.yml@main
