name: Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: KyleChamberlin/.github/workflows/rust-release.yml@main
    with:
      bin: hoe
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



