name: Rust Audit

on:
  push:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    uses: KyleChamberlin/.github/.github/workflows/rust-audit.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
