name: Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: KyleChamberlin/.github/.github/workflows/rust-release.yml@main
    with:
      bin: hoe



